import Header from "@/components/Header";
import "./globals.scss";
import { sendApiRequest } from "@/lib/utilities";

export const metadata = {
  title: "Vessel",
  description: "Generated by create next app",
};

export default async function RootLayout( { children } ) {
	const faviconUrl = await sendApiRequest( 'GET', 'vessel/v1/icon' );

	return (
		<html lang="en">
			<head>
				<link rel="icon" href={ faviconUrl } sizes="any" />
			</head>
			<body>
				<Header />
				{ children }
			</body>
		</html>
	);
}
