import Header from "@/components/Header";
import "./globals.scss";

export const metadata = {
  title: "Vessel",
  description: "Generated by create next app",
};

export default function RootLayout( { children } ) {
	return (
		<html lang="en">
			<body>
				<Header />
				{ children }
			</body>
		</html>
	);
}
