version: 2.1
jobs:
  test-php:
    docker:
      - image: cimg/php:8.2
    working_directory: ~/project/backend
    steps:
      - checkout
      - run:
          name: PHP Syntax Check
          command: |
            find . -type f -name "*.php" -exec php -l {} \;
  deploy-to-droplet:
    docker:
      - image: cimg/php:8.2
    working_directory: ~/project/backend
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "cb:e6:02:50:ea:cf:12:3f:87:02:b2:bb:4d:c6:79:c9"
      - run:
          name: Deploy to DigitalOcean Droplet
          command: |
            rsync -az --delete -e "ssh -o StrictHostKeyChecking=no" . vessel@167.99.192.92:/var/www/admin.vesselcomic.com/
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test-php
      - deploy-to-droplet:
          requires:
            - test-php
          filters:
            branches:
              only: main
