version: 2.1
jobs:
  test-php:
    docker:
      - image: cimg/php:8.2
    working_directory: ~/project/backend
    steps:
      - checkout
      - run:
          name: PHP Syntax Check
          command: |
            find . -type f -name "*.php" -exec php -l {} \;
workflows:
  version: 2
  test_backend:
    jobs:
      - test-php