name: Deploy to DigitalOcean Droplet
'on':
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            echo "Deploying themes folder..."
            cd /var/www/
            git clone -n --depth=1 --filter=tree:0 \
              git@github.com:chesterblack/vessel temp-vessel
            cd temp-vessel
            git sparse-checkout set --no-cone /backend/wp-content/themes/vessel
            git checkout
            cd ../
            rm -rf admin.vesselcomic.com/wp-content/themes/vessel
            mv temp-vessel/backend/wp-content/themes/vessel admin.vesselcomic.com/wp-content/themes
            rm -rf temp-vessel
            echo "Done"
